**YOSHNA MAHARJAN**
**'2406791'**

**6CS012 - Artificial Intelligence and Machine Learning.**

**WORKSHEET - 0**

# **4. TO-DO-TASKS - PYTHON**

# **4.1 Exercise on Functions:**

**Task - 1:**

Create a Python program that converts between different units of measurement.

• The program should:

1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).

2. Ask the user to input the value to be converted.

3. Perform the conversion and display the result.

4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:

1. Functions: Define at least one function to perform the conversion.

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

3. User Input: Prompt the user to select the conversion type and input the value.

4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.

• Conversion Options:

1. Length:

    *   Convert meters (m) to feet (ft).
    *   Convert feet (ft) to meters (m).

2. Weight:

    *   Convert kilograms (kg) to pounds (lbs).

    *   Convert pounds (lbs) to kilograms (kg).

3. Volume:

    *   Convert liters (L) to gallons (gal).

    *   Convert gallons (gal) to liters (L).


In [ ]:
def convert_units(value, from_unit, to_unit, category):
    """
    Convert a value between different units within the same category.

    Paramenters:
        value (float): The numerical value to convert.
        from_unit (str): Source unit.
        to_unit (str): Target unit
        category (str): Type of conversion.

    Returns:
        float: Converted Value.

    Raises:
        ValueError: If conversion is not supported or invalid units
    """

    if category == "length":
        if from_unit == "m" and to_unit == "ft":
            return value * 3.28084
        elif from_unit == "ft" and to_unit == "m":
            return value / 3.28084

    elif category == "weight":
        if from_unit == "kg" and to_unit == "lbs":
            return value * 2.20462
        elif from_unit == "lbs" and to_unit == "kg":
            return value / 2.20462

    elif category == "volume":
        if from_unit == "L" and to_unit == "gal":
            return value * 0.264172
        elif from_unit == "gal" and to_unit == "L":
            return value / 0.264172

    raise ValueError(f"Unsupported Conversion: {from_unit} to {to_unit} in category {category}")

def unit_converter():
    print("Unit Converter")
    print("Categories: Length, Weight, and Volume")

    try:
        category = input("Enter Category (Length/Weight/Volume): ").strip().lower()

        if category not in ["length", "weight", "volume"]:
            print('Invalid Category!')
            return

        if category == "length":
            print("Options: m and ft")
            from_unit = input("From unit (m/ft): ").strip().lower()
            to_unit = input("To unit (m/ft): ").strip().lower()

        elif category == "weight":
            print("Options: kg and lbs")
            from_unit = input("From unit (kg/lbs): ").strip().lower()
            to_unit = input('To unit (kg/lbs): ').strip().lower()

        else:
            print("Options: L and gal")
            from_unit = input("From unit (L/gal): ").strip().lower()
            to_unit = input("To unit (L/gal): ").strip().lower()

        value = float(input("Enter value: "))

        result = convert_units(value, from_unit, to_unit, category)
        print(f"{value} {from_unit} = {result:.4f} {to_unit}")

    except ValueError as e:
        print(f"Error: {e}")

    except Exception as e:
        print(f"An unexpected error occured: {e}")

if __name__ == "__main__":
    unit_converter()


Unit Converter
Categories: Length, Weight, and Volume
Enter Category (Length/Weight/Volume): weight
Options: kg and lbs
From unit (kg/lbs): kg
To unit (kg/lbs): lbs
Enter value: 100
100.0 kg = 220.4620 lbs


**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).

2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.

4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).

3. User Input: Prompt the user to select the operation and input the list of numbers.

4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value.

In [ ]:
def calculate_sum(numbers):
    """
    Return the sum of all numbers in the list
    """
    total = 0
    for n in numbers:
        total += n
    return total

def calculate_average(numbers):
    """
    Return the average of numbers in the list.
    """
    if not numbers:
        raise ValueError("Cannot calculate average of empty list.")
    return calculate_sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Return the maximum value in the lsit.
    """
    if not numbers:
        raise ValueError("Cannot find maximum of empty list.")
    maximum = numbers[0]
    for n in numbers:
        if n > maximum:
            maximum = n
        return maximum


def find_minimum(numbers):
    """
    Return the minimum value in the list.
    """
    if not numbers:
        raise ValueError("Cannot find minimum of empty list.")
    minimum = numbers[0]
    for n in numbers:
        if n < minimum:
            minimum = n
    return minimum

def list_math_operations():
    print("List Math Operations:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Select Operations (1 - 4): "))

        if choice not in [1, 2, 3, 4]:
            print("Invalid Choice!")
            return

        input_str = input("Enter numbers separated by space: ").strip()

        if not input_str:
            print("No numbers entered!")
            return

        numbers = [float(x) for x in input_str.split()]

        if choice == 1:
            result = calculate_sum(numbers)
            print(f"Sum = {result}")

        elif choice == 2:
            result = calculate_average(numbers)
            print(f"Average = {result:.4f}")

        elif choice == 3:
            result = find_maximum(numbers)
            print(f"Maximum = {result}")

        else:
            result = find_minimum(numbers)
            print(f"Minimum = {result}")

    except ValueError as e:
        print(f"Error: {e}")

    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    list_math_operations()


List Math Operations:
1. Sum
2. Average
3. Maximum
4. Minimum
Select Operations (1 - 4): 1
Enter numbers separated by space: 1 2 3 4 5 6 7 8 9 
Sum = 45.0


# **4.2 Exercise on List Manipulation:**

**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:



*   Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

*   Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Return every other element starting from index 0.
    """
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

• Requirements:

*   Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

*   Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].


In [ ]:
def get_sublist(lst, start, end):
    """
    Return sublist from start to end indices (inclusive).
    """
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

• Requirements:

*   Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.

*   Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Return a reversed copy of the list using slicing.
    """
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

• Requirements:

*   Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.

*   Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Return list without first and last elements.
    """
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.

• Requirements:

*   Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.

*   Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Return first n elements of the list.
    """
    return lst[:n]

print(get_first_n([1,2,3,4,5], 3))

[1, 2, 3]


**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

*   Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

*   Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Return lst n elements of the list.
    """
    return lst[-n:]

print(get_last_n([1,2,3,4,5], 2))

[4, 5]


**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

• Requirements:

*   Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.

*   Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """
    Return every second element starting from second-to-last, moving backward.
    """
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


# **4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

• Requirements:

*   Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.

*   Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flatten a nested list into a single dimension (one level).
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)

    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

*   Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.

*   Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Access element in nested list using a list of indices.
    """
    current = lst

    for idx in indices:
        current = current[idx]
    return current

print(access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))

6


**3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

*   Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.

*   Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Return the sum of all numbers in a nested list of any depth.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        elif isinstance(item, (int, float)):
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


**4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

*   Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.

*   Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].


In [ ]:
def remove_element(lst, elem):
    """
    Return a new nested list with all occurences of elem removed.
    """
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    return lst

print(remove_element([[1,2],[3,2],[4,5]], 2))

[[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

*   Define a function find max(lst) that takes a nested list lst and returns the maximum element.

*   Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Find the maximum number ina  nested lsit of any depth.
    """
    max_val = float("-inf")

    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        elif isinstance(item, (int, float)):
            max_val = max(max_val, item)
    return max_val if max_val != float("-inf") else None

print(find_max([[1,2],[3,[4,5]],6]))

6


**6. Count Occurrences of an Element in a Nested List:**

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

*   Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.

*   Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.


In [ ]:
def count_occurrences(lst, elem):
    """
    Count how many times elem appears in a nested list.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]], 2))

3


**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

*   Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

*   Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].


In [ ]:
def deep_flatten(lst):
    """
    Completely flatten a list of any nesting depth.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

*   Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.

*   Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.


In [ ]:
def average_nested(lst):
    """
    Calculate the average of all numbers in a nested list.
    """
    total = sum_nested(lst)
    count = count_occurrences(lst, lambda x: isinstance(x, (int, float)))

    def count_numbers(l):
        c = 0
        for item in l:
            if isinstance(item, list):
                c += count_numbers(item)
            elif isinstance(item, (int, float)):
                c += 1
        return c

    count = count_numbers(lst)

    return total / count if count > 0 else 0

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


# **10. TO-DO-TASKS - NumPy**

In [2]:
import numpy as np

# **10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

Complete the following Tasks:

1. Initialize an empty array with size 2X2.

2. Initialize an all one array with size 4X2.

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
# 1. Initialize an empty array with size 2X2.
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_2x2, "\n")

# 2. Initialize an all one array with size 4X2.
ones_4x2 = np.ones((4, 2))
print("2. All ones 4x2 array:\n", ones_4x2, "\n")

# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
filled_array = np.full((3, 5), 7)
print("3. 3×5 array filled with 7:\n", filled_array, "\n")

# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
reference = np.array([[1.5, 2.5], [3.5, 4.5]])
zeros_like = np.zeros_like(reference)
print("4. Zeros like reference array:\n", zeros_like, "\n")

# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
ones_like = np.ones_like(reference)
print("5. Ones like reference array:\n", ones_like, "\n")

# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. Array from list [1,2,3,4]:\n", array_from_list)
print("   Type:", type(array_from_list), "\n")

1. Empty 2x2 array:
 [[3.75667350e-315 0.00000000e+000]
 [6.81301627e-310 5.76313742e-317]] 

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. 3×5 array filled with 7:
 [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]] 

4. Zeros like reference array:
 [[0. 0.]
 [0. 0.]] 

5. Ones like reference array:
 [[1. 1.]
 [1. 1.]] 

6. Array from list [1,2,3,4]:
 [1 2 3 4]
   Type: <class 'numpy.ndarray'> 



**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}

3. Create a 3X3 identity matrix.{Hint:np.eye()}

4. Create a random array of size 30 and find the mean of the array. {Hint:check for np.random.random() and array.mean() function}

5. Create a 10X10 array with random values and find the minimum and maximum values.

6. Create a zero array of size 10 and replace 5th element with 1.

7. Reverse an array arr = [1,2,0,0,4,0].

8. Create a 2d array with 1 on border and 0 inside.

9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [ ]:
# 1. Array with values ranging from 10 to 49
arr_10_to_49 = np.arange(10, 50)
print("1. Values from 10 to 49:\n", arr_10_to_49, "\n")

# 2. 3×3 matrix with values ranging from 0 to 8
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("2. 3×3 matrix 0→8:\n", matrix_0_to_8, "\n")

# 3. 3×3 identity matrix
identity_3x3 = np.eye(3)
print("3. 3×3 identity matrix:\n", identity_3x3, "\n")

# 4. Random array of size 30 → find mean
rand_30 = np.random.random(30)
mean_30 = rand_30.mean()
print("4. Random array of 30 elements (first 5 shown):", rand_30[:5], "...")
print("   Mean =", mean_30, "\n")

# 5. 10×10 random array → min and max
rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("5. 10×10 random array → min =", min_val, ", max =", max_val, "\n")

# 6. Zero array of size 10, replace 5th element (index 4) with 1
zeros_10 = np.zeros(10)
zeros_10[4] = 1
print("6. Zeros with 5th position = 1:\n", zeros_10, "\n")

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
# or: np.flip(arr)
print("7. Original:", arr)
print("   Reversed :", reversed_arr, "\n")

# 8. 2D array with 1 on border and 0 inside (e.g. 5×5)
border = np.ones((5, 5), dtype=int)
border[1:-1, 1:-1] = 0
print("8. 5×5 border 1's, inside 0's:\n", border, "\n")

# 9. 8×8 checkerboard pattern (two common styles shown)
checker = np.zeros((8, 8), dtype=int)
checker[::2, ::2] = 1
checker[1::2, 1::2] = 1
print("9A. 8×8 checkerboard (0 top-left):\n", checker, "\n")

1. Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3×3 matrix 0→8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3×3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random array of 30 elements (first 5 shown): [0.84048764 0.33558565 0.00680149 0.42997956 0.63237846] ...
   Mean = 0.4946120075437793 

5. 10×10 random array → min = 0.02367331312458687 , max = 0.99223527619038 

6. Zeros with 5th position = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] 

7. Original: [1 2 0 0 4 0]
   Reversed : [0 4 0 0 2 1] 

8. 5×5 border 1's, inside 0's:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]] 

9A. 8×8 checkerboard (0 top-left):
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]] 



**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.

2. Subtract the two array.

3. Multiply the array with any integers of your choice.

4. Find the square of each element of the array.

5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.

7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [ ]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x =\n", x, "\n")
print("y =\n", y, "\n")
print("v =", v, "\n")
print("w =", w, "\n")

# 1. Add the two array.
print("1. x + y =\n", x + y, "\n")

# 2. Subtract the two array.
print("2. x - y =\n", x - y, "\n")

# 3. Multiply the array with any integers of your choice.
print("3. x × 4 =\n", x * 4, "\n")

# 4. Find the square of each element of the array.
print("4. x² (element-wise) =\n", x ** 2, "\n")
print("   y² (element-wise) =\n", y ** 2, "\n")

# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("5. Dot products:")
print("   v · w  =", np.dot(v, w))
print("   x · v  =", np.dot(x, v))
print("   x · y  =\n", np.dot(x, y), "\n")

# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
print("6. Concatenate x and y along rows:")
print(np.vstack((x, y)))

print("\nConcatenate v and w along columns:")
print(np.concatenate((v[:,np.newaxis], w[:,np.newaxis]), axis=1), "\n")

# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print("7. Trying np.concatenate((x, v), axis=0), will raise error.")
print("   Reason: x is 2×2 (2D), v is 1D (shape (2,))")
print("   NumPy requires matching dimensions except along the concatenation axis.\n")

print("   Correct ways:")
print("    -> Treat v as row vector:")
print(np.vstack((x, v[np.newaxis, :])))

print("\n    -> Or treat v as column vector:")
print(np.hstack((x, v[:, np.newaxis])))


x =
 [[1 2]
 [3 5]] 

y =
 [[5 6]
 [7 8]] 

v = [ 9 10] 

w = [11 12] 

1. x + y =
 [[ 6  8]
 [10 13]] 

2. x - y =
 [[-4 -4]
 [-4 -3]] 

3. x × 4 =
 [[ 4  8]
 [12 20]] 

4. x² (element-wise) =
 [[ 1  4]
 [ 9 25]] 

   y² (element-wise) =
 [[25 36]
 [49 64]] 

5. Dot products:
   v · w  = 219
   x · v  = [29 77]
   x · y  =
 [[19 22]
 [50 58]] 

6. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
[[ 9 11]
 [10 12]] 

7. Trying np.concatenate((x, v), axis=0), will raise error.
   Reason: x is 2×2 (2D), v is 1D (shape (2,))
   NumPy requires matching dimensions except along the concatenation axis.

   Correct ways:
    -> Treat v as row vector:
[[ 1  2]
 [ 3  5]
 [ 9 10]]

    -> Or treat v as column vector:
[[ 1  2  9]
 [ 3  5 10]]


**Problem - 4: Matrix Operations:**

• For the following arrays:

    A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

    Prove following with Numpy:

    1. Prove A.A−1 = I.

    2. Prove AB ̸= BA.

    3. Prove (AB) T = BTAT.

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("A =\n", A)
print("B =\n", B, "\n")

# 1. Prove A.A⁻¹ = I

print("1. Prove A.A⁻¹ = I")

# Inverse of A
A_inv = np.linalg.inv(A)

# Multiply A and its inverse
result = np.dot(A, A_inv)

print("Inverse of A:\n", A_inv)
print("A * A^-1:\n", result, "\n")

# 2. Prove AB ≠ BA (in general)

print("2. Prove AB ≠ BA (in general)")

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("BA =\n", BA, "\n")

# 3. Prove (AB)ᵀ = Bᵀ Aᵀ

print("3. Prove (AB)ᵀ = Bᵀ Aᵀ")

# Left side
left = (np.dot(A, B)).T

# Right side
right = np.dot(B.T, A.T)

print("(AB)^T =\n", left)
print("B^T A^T =\n", right)

print("Are they equal?", np.allclose(left, right))

A =
 [[3 4]
 [7 8]]
B =
 [[5 3]
 [2 1]] 

1. Prove A.A⁻¹ = I
Inverse of A:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]] 

2. Prove AB ≠ BA (in general)
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]] 

3. Prove (AB)ᵀ = Bᵀ Aᵀ
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Are they equal? True


• Solve the following system of Linear equation using Inverse Methods.

    2x − 3y + z = −1

    x − y + 2z = −3

    3x + y − z = 9

    {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [20]:
# Coefficient matrix A
A_sys = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
])

# Right-hand side
b = np.array([-1, -3, 9])

print("A =\n", A_sys)
print("b =", b, "\n")

# Compute inverse
A_inv_sys = np.linalg.inv(A_sys)

# Solve X = A⁻¹ b
x_solution = np.dot(A_inv_sys, b)

print("Solution using inverse:")
print("x =", round(x_solution[0], 6))
print("y =", round(x_solution[1], 6))
print("z =", round(x_solution[2], 6), "\n")

# Verification
print("Verification: Solve for: AX = B")
print("B = ", np.dot(A_sys, x_solution))

A =
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
b = [-1 -3  9] 

Solution using inverse:
x = 2.0
y = 1.0
z = -2.0 

Verification: Solve for: AX = B
B =  [-1. -3.  9.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [21]:
x_solve = np.linalg.inv(A_sys).dot(b)
print("Solution using np.linalg.inv(): ", x_solve)
print("np.linalg.inv is more stable and usually faster than explicit inverse")

Solution using np.linalg.inv():  [ 2.  1. -2.]
np.linalg.inv is more stable and usually faster than explicit inverse


# **10.2 Experiment: How Fast is Numpy?**


In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

In [13]:
import time

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [14]:
import numpy as np
import time

n = 1000000

# Python Lists
list1 = list(range(n))
list2 = list(range(n))

start = time.time()

result = [list1[i] + list2[i] for i in range(n)]

end = time.time()
print("Python List Addition Time:", end - start)


# NumPy Arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()

result_np = arr1 + arr2

end = time.time()
print("NumPy Addition Time:", end - start)

Python List Addition Time: 0.06087994575500488
NumPy Addition Time: 0.0021240711212158203


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [15]:
# Python Lists
start = time.time()

result = [list1[i] * list2[i] for i in range(n)]

end = time.time()
print("Python List Multiplication Time:", end - start)


# NumPy Arrays
start = time.time()

result_np = arr1 * arr2

end = time.time()
print("NumPy Multiplication Time:", end - start)

Python List Multiplication Time: 0.1165008544921875
NumPy Multiplication Time: 0.001016378402709961


**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [16]:
# Python Lists
start = time.time()

dot = 0
for i in range(n):
    dot += list1[i] * list2[i]

end = time.time()
print("Python List Dot Product Time:", end - start)


# NumPy Arrays
start = time.time()

dot_np = np.dot(arr1, arr2)

end = time.time()
print("NumPy Dot Product Time:", end - start)

Python List Dot Product Time: 0.13768839836120605
NumPy Dot Product Time: 0.0010635852813720703


**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.


In [17]:
size = 1000

# Python List Matrices
A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()

C = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            C[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Python Matrix Multiplication Time:", end - start)

Python Matrix Multiplication Time: 190.58975839614868


In [18]:
A_np = np.ones((size, size))
B_np = np.ones((size, size))

start = time.time()

C_np = np.dot(A_np, B_np)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

NumPy Matrix Multiplication Time: 0.05330657958984375
